# для запуска из терминала Идеи создаем jar командой " ./mvnw spring-boot:build-image " или " mvn clean package "
# затем из папки с jar файлом выполняем команду
# java -jar -Dspring.profiles.active=england eureka-server-0.2.jar
# java -jar -Dspring.profiles.active=australia eureka-server-0.1.jar
# при создании двух образов надо поменять номер snapshot

spring:
  config:
    activate:
      on-profile: default
  application:
    name: eureka-server

server:
  port: ${PORT:8761}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    instance-info-replication-interval-seconds: 10
    serviceUrl:
      defaultZone: http://eureka-server-au.com:9001/eureka/, http://eureka-server-en.com:9002/eureka/
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    eviction-interval-timer-in-ms: 50000
    wait-time-in-ms-when-sync-empty: 5
  instance:
    hostname: eureka-server.com

---
spring:
  config:
    activate:
      on-profile: australia
  application:
    name: eureka-server-clustered
server:
  port: 9001
eureka:
  instance:
    hostname: eureka-server-au.com
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server-en.com:9002/eureka/, http://eureka-server.com:8761/eureka/
#      defaultZone: http://eureka-server-en.com:9002/eureka/

---

spring:
  config:
    activate:
      on-profile: england
  application:
    name: eureka-server-clustered
server:
  port: 9002
eureka:
  instance:
    hostname: eureka-server-en.com
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server-au.com:9001/eureka/, http://eureka-server.com:8761/eureka/
#      defaultZone: http://eureka-server-au.com:9001/eureka/